# fly.toml app configuration file generated for noyakka-core on 2026-01-26T23:33:34+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noyakka-core'
primary_region = 'syd'

[env]
  GIT_SHA = "unknown"
  BUILD_TIME = "unknown"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = "noyakka_data"
  destination = "/data"

[deploy]
  release_command = "sh -c 'if [ \"$SKIP_MIGRATIONS\" = \"1\" ]; then echo \"Skipping migrations\"; else npx prisma migrate deploy; fi'"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
